### ISSUE TITLE
Ambiguity in examples

### ISSUE THREAD

**Issue by kurtcagle** [w3c/data-shapes#36]
In a number of examples, you have both the subject and object being of type Person. The problem with this is that it does not make it clear whether things like sh:class and sh:targetClass are referring to the subject or object. Adding in something like an inSchool property would resolve that ambiguity.

**Comment by HolgerKnublauch** [comment]
Hi Kurt, I have changed the example in sh:class to be between Persons and Address. But I am struggling a bit with a suitable replacement for the other case, the main example (section 1.4). There we are using ex:child as the main relation because it can be nicely used to illustrate paths, and the use of paths to define custom labels via sh:name. One could say that this feature doesn't need to be introduced there as it may be too complex already, but would you have a suggestion for a simple-enough replacement that has a similar scenario (with an inverse property). I could go with Person -> worksFor -> Organization and then use the inverse of ex:manager, but I am worried that as soon as I have two classes then other people will get even more confused.

**Comment by kurtcagle** [comment]
I think that the example you gave (with worksFor and manager) is a good
one, and I would be less concerned about having multiple classes there. The
problem with parent/child by itself is that this often describes a fairly
broad set of relationships, not just a familial one, while the business
case is much more obvious as a distinct example, and provides a second set
of examples to reality check the usage. Also, keep in mind that most people
are not going to be reading the spec linearly - they'll almost certainly
dip into it mid-document - so the cohesiveness of the pedagogy is not as
important there.

My two cents worth, anyway.

I think as a worse case scenario, it may not hurt to plan a primer on SHACL
as a non-normative document.


Kurt Cagle
Founder, Semantical LLC
kurtcagle@gmail.com
443-837-8725

**Comment by HolgerKnublauch** [comment]
I have updated the example as discussed. Please take a look and close if satisfied.

**Comment by HolgerKnublauch** [comment]
Closing as decided in https://www.w3.org/2017/03/22-shapes-minutes.html#item07
