### ISSUE TITLE
SPARQL additions 

### ISSUE THREAD

**Issue by kurtcagle** [w3c/data-shapes#38]
I'm coming to this late, so I don't know whether this has been addressed, but has any coordination been done with the SPARQL WG concerning invocation of SHACL from within SPARQL queries? For instance, it would seem to be a safe bet that a function such as

```
select ?s where {
?s a class:Person.
filter (validate(?s,graph:validators)) 
}
```
where graph:validators was a reference to a shacl graph would be a logical use case for invocation. validate() here would return a Boolean. The query would only return a reference IRI if it was in fact valid according to the validate() function.

A similar SPARQL function - report() - would perform a similar action, but the result set in that case would be the result set from a SHACL report. 

```
insert {graph <report> {?rs ?rp ?ro} using graph <foo> where {
     ?s a class:Person.
     bind (report(?s,graph:shacl) as {?rs ?rp ?ro})
}
```

I'd have to go back and check the syntax on the bind, but the idea should be clear - you're making the triples of the report from validating against the relevant shack graph available to the insert clause. 

Note - I realize this is probably outside the scope of the SHACL spec, more a question as to whether there's been any discussion on this issue. Feel free to close without comment.

**Comment by HolgerKnublauch** [comment]
Yes this topic was discussed (controversially) in the WG. Earlier versions of SHACL included a function sh:hasShape, but this got deleted because it would require changes to SPARQL engines and because it was adding complexity (e.g. recursion) to the language, making SPARQL queries harder to control.

Once sh:hasShape had been taken out, I have moved it into my own namespace as tosh:hasShape supported by TopBraid API and products. It would be ideal if multiple vendors could agree on such a function.

Note that we still plan to publish a WG Note about "Advanced SPARQL features" which may theoretically include a description of such a function.

On the latter use case (INSERT ...) I would argue this takes it a bit too far and such invocation is better handled by other ways.

(For house-keeping, could you suggest how we proceed with this ticket. It feels like a useful input on future work but not actionable for CR of the main spec since the sh:hasShape function had already been discussed there).

**Comment by kurtcagle** [comment]
Close it? That's the last real item I have for the list, and if there's an
intent for an advanced SPARQL features addendum, then it doesn't make sense
to keep it open.


Kurt Cagle
Founder, Semantical LLC
kurtcagle@gmail.com
443-837-8725
