### ISSUE TITLE
Standardized way to add indications of text direction

### ISSUE THREAD

**Issue by r12a** [w3c/data-shapes#40]
[note from @sandhawke ]
> 2. However, in RDF, as far as I know, there's no standardized way to
> add indications of text direction in the metadata around text.
> rdf:HTML and rdf:XMLLiteral values have their normal ways of doing dir
> inside the data, and of course text strings have their normal (but
> imperfect) ways to do it (eg using the first strong directional
> character).  I expect if a way were standardized for doing this in
> RDF, it would simply work in SHACL.   If you know of a design for
> doing this, we could confirm this expectation.

[reply from @fsasaki ]
This is an issue that has come up in several discussions in the last year, e.g. in relation to Web annotation. See the related resolution here
https://github.com/w3c/web-annotation/issues/224#issuecomment-219953153
the annotation model provides a textDirection relationship to express directionality. It may be hard to generalize this for RDF, but it may help SHACL. From reading the SHACL spec, it seems this topic is relevant for all definitions that also have language tags. That is: message / resultMessage, name, description.

**Comment by HolgerKnublauch** [comment]
Thanks, the discussion in the link above is interesting - I also thought that ltr vs rtl could be easily derived from the given language tags, but that doesn't seem to work.

In SHACL we had long discussions on how far we want to go with these non-validation properties. Text direction would not cause validation results, so they are in the UI camp only. Some people in the WG were pretty strongly in favor of making SHACL a pure validation language, without such annotation properties. We ended up with some (sh:name etc), but we acknowledge that we cannot cover all use cases. Other namespaces will add to the existing SHACL definitions. For example we have a custom namespace to declare UI widgets for a given SHACL property shape.

My preference would be to leave it to 3rd party namespaces and future extensions to cover text direction. Otherwise, we'd need to invent something that is better handled on lower level, and that may require some new form of reification.

**Comment by fsasaki** [comment]
> My preference would be to leave it to 3rd party namespaces and future extensions to cover text direction. Otherwise, we'd need to invent something that is better handled on lower level, and that may require some new form of reification.

Would be fine by me, but let's see what other i18n WG colleagues say.

**Comment by HolgerKnublauch** [comment]
Closing as decided in https://www.w3.org/2017/03/22-shapes-minutes.html#item02
