### ISSUE TITLE
minor mistake in spec - ex:unsinged

### ISSUE THREAD

**Issue by CaptSolo** [w3c/data-shapes#9]
A mistake in the code example in ( https://github.com/w3c/data-shapes/blob/gh-pages/shacl/index.html ):

```
inst:Issue3 ex:state **ex:unsinged**
```

while the text following this example refers to the same property value as **ex:unsigned**

**Comment by agryman** [comment]
Thanks for the report, but if you read the text following the code you'll see that this is an intensional misspelling to illustrate how SHACL can be used to find typos in RDF code. Here's the text: "Validating the second node would determine that inst:Issue3 violates the constraint on values for ex:state, because ex:unsigned is not in the list of allowed values, "

**Comment by CaptSolo** [comment]
Look at it closer. It's a small mistake and easy to overlook - but still - the text referring to the incorrect (misspelled) property misspells it yet another way:

The text refers to the **incorrect** property [used intentionally] in the code as "ex:unsigned" (just as you quoted above) while the **incorrect** property value listed in the code is "ex:unsinged".

**Comment by agryman** [comment]
@CaptSolo thanks for the clarification. I fixed the Editor's Draft: http://w3c.github.io/data-shapes/shacl/
Please review it and close this issue if the fix is OK.

**Comment by CaptSolo** [comment]
Thanks - it's OK now.
