### ISSUE TITLE
Incorrect test suite result for `core/property/uniqueLang-002`?

### ISSUE THREAD

**Issue by dthume** [w3c/data-shapes#98]
Apologies if I've misunderstood something, but the `core/property/uniqueLang-002` test defines a shape:

```
ex:s1 a sh:PropertyShape ;
  sh:targetNode ex:i ;
  sh:path ex:message ;
  sh:uniqueLang "1"^^xsd:boolean .
```

which is then applied to the data graph:

```
ex:i ex:message "HI"@en, "Hi"@en .
```

The test suite indicates that the expected result is:

```
[ a sh:ValidationReport ;
  sh:conforms "true"^^xsd:boolean ]
```

But this seems incorrect and indeed the shacl.org playground produces a validation result (as I'd expect):

```
[
	a sh:ValidationResult ;
	sh:resultSeverity sh:Violation ;
	sh:sourceConstraintComponent sh:UniqueLangConstraintComponent ;
	sh:sourceShape ex:s1 ;
	sh:focusNode ex:i ;
	sh:resultPath ex:message ;
	sh:resultMessage "Language "en" has been used by 2 values" ;
	sh:resultMessage "Language "{?lang}" used more than once" ;
] .
```

Is the test in error?

**Comment by HolgerKnublauch** [comment]
Since this has caused confusion before, I have just added a comment into the shapes file:

Note that the value above is "1"^^xsd:boolean, which is distinct from "true"^^xsd:boolean.
Only true is mentioned in the spec, meaning that "1" will not activate the constraint
and the constraint is being ignored.

The SHACL playground cannot distinguish between these cases because the underlying RDF parsing API treats all boolean literals uniformly, so my code is converting all "1" to "true".

If that clarifies it, can the ticket be closed?

**Comment by dthume** [comment]
Urm, it clarifies the reason the specific test is the way it is, but confuses me on another matter, which I hope you don't mind me asking here: are SHACL engines expected / required to operate on the _lexical_ representation of literals rather than their values in order to be conformant? Lexical `true` and `1` are both considered to map to the value `true` in `xsd:boolean`.

I ask because I've been using SHACL as part of some APIs, and I'd like to make sure any validation code I have is correct. When reading the spec I'd assumed that anywhere I saw statements like "literals with datatype xsd:boolean" it was the value of said literals we were interested in (since otherwise why bother requiring a datatype?).

**Comment by HolgerKnublauch** [comment]
It depends on a case-by-case basis. If the spec says <code>true</code> then this is definitely only "true"^^xsd:boolean. And the relevant paragraph says "If $uniqueLang is <code>true</code> then f..." The test cases are there to clarify the intention, although the prose in the spec is supposed to be specific too. The previous statements are about the shapes graphs. In data graphs it also depends on the semantics of the constraint component. For example sh:hasValue requires term equivalence, so "01"^^xsd:integer and "1"^^xsd:integer would be distinct values.

**Comment by dthume** [comment]
OK, I suppose that makes sense, although I confess I hadn't picked up on it when implementing the spec.

**Comment by ashleysommer** [comment]
@HolgerKnublauch @dthume 
I've just come across this same issue implementing pySHACL. The Python RDFLib RDF Literal implementation interprets lexical `"true"^^xsd:boolean` _and_ `"1"^^xsd:boolean` as xsd:boolean `true`.
In this case, due to the nature of the python language, I was able to slightly modify (patch) the way the RDFLib Literal builder checks for xsd:boolean Trueness, and it fixes this test for me.
